In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from dateutil.parser import parse
import numpy as np

In [2]:
nombres = np.genfromtxt('../002_datos/DatosTemixcoEsolmet2018.csv',dtype='U',delimiter=',',max_rows=1,
                       skip_header=2)
nombres

for i,nombre in enumerate(nombres):
    print(i,nombre)
    
nombres[0]  = 'tiempo'
nombres[1]  = 'Idirecta'
nombres[2]  = 'Iglobal'
nombres[3]  = 'Idifusa'
nombres[4]  = 'UV'
nombres[5]  = 'To'
nombres[6]  = 'HR'
nombres[7]  = 'Wspeed'
nombres[8]  = 'Presion'

0 Fecha
1 Directa
2 Global
3 Difusa
4 UV
5 Temperatura
6 Humedad
7 Viento Vel.
8 PresiÃ²n Bar.

In [3]:
data = pd.read_csv('../epw/DatosTemixcoEsolmet2018.csv',skiprows=[0,1,2,3,4,],names=nombres,
                  index_col=0,parse_dates=True)
data

,Idirecta,Iglobal,Idifusa,UV,To,HR,Wspeed,Presion
tiempo,,,,,,,,
2019-03-05 00:00:00,0.000,0.000,0.0,0.186,23.02,47.67,3.463,876.0016
2019-03-05 00:10:00,0.000,0.000,0.0,0.183,22.95,48.15,2.541,875.9597
2019-03-05 00:20:00,0.000,0.000,0.0,0.184,23.01,47.78,1.763,875.8949
2019-03-05 00:30:00,0.000,0.000,0.0,0.183,22.83,47.67,2.161,875.8536
2019-03-05 00:40:00,0.000,0.000,0.0,0.185,22.69,48.32,1.409,875.6332
...,...,...,...,...,...,...,...,...
2019-06-24 23:20:00,0.132,0.000,0.0,0.000,23.52,76.54,0.467,877.1298
2019-06-24 23:30:00,0.150,0.000,0.0,0.000,23.54,77.08,0.427,877.1132
2019-06-24 23:40:00,0.112,0.000,0.0,0.000,23.39,79.91,0.578,877.0811
2019-06-24 23:50:00,0.155,0.000,0.0,0.000,23.16,80.50,2.258,877.1050
2019-06-25 00:00:00,0.012,0.184,0.0,0.000,22.48,84.40,2.867,876.8762

In [4]:
data.to_csv('../epw/datalimpia.csv')